title: "MCSMIP"
author: "MCSMIP"
description: "Mesoscale Convective Systems tracking Method Intercomparison"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            MCSMIP
tagline:          'A cloud tracking intercomparison project'
description:      'Mesoscale Convective Systems tracking Method Intercomparison'
url:              http://hyde.getpoole.com
baseurl:          /

remote_theme: "poole/hyde"

author:
  name:           'Julia Kukulies'

paginate:         5


github:
  repo:           https://github.com/WACCEM/MCSMIP-DYAMOND
  
plugins:
 - jekyll-feed
 - jekyll-remote-theme
 - jekyll-gist

