name: Deploy PR Preview to GitHub Pages

on:
  pull_request:
    types: [opened, synchronize, reopened]


jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      # Check out the PR branch
      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 1  # Only fetch the latest commit for efficiency

      # Set up Ruby with version 3.1.x
      - name: Set up Ruby 3.1.x
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1  # Ensuring Ruby 3.1.x is used

      # Install dependencies (this should work with Bundler 3.x now)
      - name: Install dependencies
        run: |
          gem install bundler # Install latest Bundler (3.x) which is compatible with Ruby >= 3.1.0
          bundle install

      # Build the site
      - name: Build the site with Jekyll
        run: |
          bundle exec jekyll build

      # Deploy to GitHub Pages Preview
      - name: Deploy to GitHub Pages Preview
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # Location of your built site
          publish_branch: gh-pages  # GitHub Pages branch
          destination_dir: preview/${{ github.event.pull_request.number }}  # Preview folder
