name: Deploy PR Preview to GitHub Pages

on:
  pull_request:
    branches:
      - sidebar  # Replace with your PR branch name, or leave it as is to target all PRs

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      # Check out the PR branch
      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 1  # Only fetch the latest commit for efficiency

      # Set up Ruby version 2.7.8 (compatible with Bundler 2.4.22)
      - name: Set up Ruby 2.7.8 (for Bundler 2.4.22 compatibility)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.8  # This ensures Ruby 2.7.x is installed

      # Install Bundler 2.4.22 (for Ruby 2.7)
      - name: Install Bundler 2.4.22
        run: |
          gem install bundler -v 2.4.22

      # Install dependencies
      - name: Install dependencies
        run: |
          bundle install

      # Build the site
      - name: Build the site with Jekyll
        run: |
          bundle exec jekyll build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages Preview
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # This is where your built site lives (it might be different based on your setup)
          publish_branch: gh-pages  # The branch that serves your GitHub Pages site
          destination_dir: preview/${{ github.event.pull_request.number }}  # Deploy the PR to a specific folder under /preview/<pr-number>
