name: Deploy PR Preview to GitHub Pages

on:
  pull_request:
    # This will trigger on PRs to any branch, not just "sidebar"
    branches:
      - '*'  # This means "any branch" (wildcard for all branches)

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the PR branch
      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 1  # Fetch only the latest commit for efficiency

      # Step 2: Set up Ruby (or adjust based on your site generator, e.g., Jekyll)
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7  # Update Ruby version if needed for your Jekyll setup

      # Step 3: Install dependencies (adjust based on your site generator)
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      # Step 4: Build the site using Jekyll (or your static site generator)
      - name: Build the site with Jekyll
        run: |
          bundle exec jekyll build

      # Step 5: Deploy to GitHub Pages (PR Preview)
      - name: Deploy to GitHub Pages Preview
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # This is where your built site lives
          publish_branch: gh-pages  # Branch where your GitHub Pages site is deployed
          destination_dir: preview/${{ github.event.pull_request.number }}  # Unique subfolder for each PR, e.g., /preview/27
