name: Deploy PR Preview to GitHub Pages

on:
  pull_request:
    branches:
      - sidebar  # Replace with your PR branch name, or leave it as is to target all PRs

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      # Check out the PR branch
      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 1  # Only fetch the latest commit for efficiency

      # Set up Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0  # You can use a higher Ruby version if necessary

      # Install dependencies based on the Ruby version
      - name: Install dependencies
        run: |
          # Check Ruby version and install compatible Bundler version
          RUBY_VERSION=$(ruby -v)
          if [[ "$RUBY_VERSION" =~ 2.7 ]]; then
            gem install bundler -v 2.4.22
          else
            gem install bundler
          fi
          bundle install

      # Build the site
      - name: Build the site with Jekyll
        run: |
          bundle exec jekyll build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages Preview
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # This is where your built site lives (it might be different based on your setup)
          publish_branch: gh-pages  # The branch that serves your GitHub Pages site
          destination_dir: preview/${{ github
