name: Deploy PR Preview to GitHub Pages

on:
  pull_request:
    types: [opened, synchronize, reopened]  # Trigger for all PR events

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      # Check out the PR branch
      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      # Set up Hugo (Install Hugo as a NodeJS-based site generator)
      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2

      # Build the Hugo site
      - name: Build the site with Hugo
        run: hugo

      # Deploy to GitHub Pages Preview
      - name: Deploy to GitHub Pages Preview
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Hugo output folder
          publish_branch: gh-pages
          destination_dir: preview/${{ github.event.pull_request.number }}
